### ISSUE TITLE
ANSI preview.... how?

### ISSUE THREAD

**Issue by Anobium** [lloiser/language-ansi-styles#4]
I have installed the extension.

How to get to preview an ANSI formatted file?

Assume that I have an ANSI file.  I do.  :-)

**Comment by lloiser** [comment]
You have to select the `Ansi Styles` grammar https://flight-manual.atom.io/using-atom/sections/grammar/

**Comment by Anobium** [comment]
I have now selected. Vert grateful.

When I ASCIIDOCS I can see a preview.  Can I do same in ANSI ?

**Comment by Anobium** [comment]
![image](https://user-images.githubusercontent.com/17933379/65900655-6a5ff900-e3ae-11e9-9289-e71bbf3c9ac5.png)

This is ANSI. But, still no joy at seeing a preview.

**Comment by lloiser** [comment]
Check out the other open issue: https://github.com/lloiser/language-ansi-styles/issues/1

It's also possible that something has changed in atom. I haven't used this package for 2 years myself...

Also, feel free to fix this problem, I will gladly accept a pull request :)

**Comment by Anobium** [comment]
I would not know how to fix.  

I may have to give up.
